// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pgKjZZpIApuLEG138NJ9lEVUz-9CQUU',
    appId: '1:227257601473:android:3ca68497ee3b414e26f340',
    messagingSenderId: '227257601473',
    projectId: 'bonifatus-calculator',
    storageBucket: 'bonifatus-calculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrvG32aZxW4hDImPGaGb-8rfNdwEqUIko',
    appId: '1:227257601473:ios:39be4332ba20c20f26f340',
    messagingSenderId: '227257601473',
    projectId: 'bonifatus-calculator',
    storageBucket: 'bonifatus-calculator.firebasestorage.app',
    androidClientId: '227257601473-9e91hbr23kg7ohhatdtvga0a54l1u6vq.apps.googleusercontent.com',
    iosClientId: '227257601473-a121gfc90kaq6ovno1jv5lej15ijcp7c.apps.googleusercontent.com',
    iosBundleId: 'com.bonifatus.app',
  );
}
